

#pragma once

#define SPARKY_INCOMING_PORT 8888
#define SPARKY_OUTGOING_PORT 7777

#define OF_INCOMING_PORT SPARKY_OUTGOING_PORT
#define OF_OUTGOING_PORT SPARKY_INCOMING_PORT

#define PACKET_TYPE_DISCOVERY   0
#define PACKET_TYPE_HEARTBEAT   1
#define PACKET_TYPE_COLOR       2
